export const INSERTDATA = 'INSERTDATA';
export const GETDATA = 'GETDATA';
export const HOLIDAYGETDATA = 'HOLIDAYGETDATA';
export const HOLIDAYSHOPGETDATA = 'HOLIDAYSHOPGETDATA';
export const MANAGEGETDATA = 'MANAGEGETDATA';
export const PICKUPGETDATA = 'PICKUPGETDATA';