/**** Product Category ****/
export const GETPRODUCTCAT = 'GETPRODUCTCAT';
export const GETALLPRODUCTCAT = 'GETALLPRODUCTCAT';
export const UPDATEPRODUCTCAT = 'UPDATEPRODUCTCAT';
export const ADDPRODUCTCAT = 'ADDPRODUCTCAT';
export const DELETEPRODUCTCAT = 'DELETEPRODUCTCAT';

/**** Config ****/
export const HOLIDAYGETDATA = 'HOLIDAYGETDATA';
export const HOLIDAYSHOPGETDATA = 'HOLIDAYSHOPGETDATA';
export const MANAGEGETDATA = 'MANAGEGETDATA';
export const PICKUPGETDATA = 'PICKUPGETDATA';

/**** Product ****/
export const GETPRODUCT = 'GETPRODUCT';
export const GETALLPRODUCT = 'GETALLPRODUCT';
export const UPDATEPRODUCT = 'UPDATEPRODUCT';
export const ADDPRODUCT = 'ADDPRODUCT';
export const DELETEPRODUCT = 'DELETEPRODUCT';
