export const INSERTDATA = 'INSERTDATA'
export const GETDATA = 'GETDATA'
export const HOLIDAYGETDATA = 'HOLIDAYGETDATA'
export const HOLIDAYSHOPGETDATA = 'HOLIDAYSHOPGETDATA'
export const MANAGEGETDATA = 'MANAGEGETDATA'
export const PICKUPGETDATA = 'PICKUPGETDATA'

//Product
export const GETPRODUCT = 'GETPRODUCT'
export const GETALLPRODUCT = 'GETALLPRODUCT'
export const UPDATEPRODUCT = 'UPDATEPRODUCT'
export const ADDPRODUCT = 'ADDPRODUCT'
export const DELETEPRODUCT = 'DELETEPRODUCT'
